### ISSUE TITLE
RunComputeEmissionsEvents

### ISSUE THREAD

**Issue by neda-git** [eqasim-org/ile-de-france#167]
Hello everyone. Some help would be appreciated. I'm struggling with running RunComputeEmissionsEvents, how can i solve this problem (inconsistent), i'm really confused. 

 2023-03-28T10:43:30,986 INFO Injector:96
2023-03-28T10:43:30,986 INFO Injector:99 === printInjector end ===
2023-03-28T10:43:30,989 INFO EmissionModule:141 entering createLookupTables
2023-03-28T10:43:34,668 INFO EmissionModule:156 leaving createLookupTables
2023-03-28T10:43:34,795 INFO EmissionModule:196 entering createEmissionHandlers
Exception in thread "main" com.google.inject.ProvisionException: Unable to provision, see the following errors:

Error injecting constructor, java.lang.RuntimeException: inconsistent
at org.matsim.contrib.emissions.EmissionModule.(EmissionModule.java:65)
while locating org.matsim.contrib.emissions.EmissionModule
1 error
at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226)
at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1053)
at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1086)
at org.eqasim.ile_de_france.emissions.RunComputeEmissionsEvents.main(RunComputeEmissionsEvents.java:72)
Caused by: java.lang.RuntimeException: inconsistent
at org.matsim.contrib.emissions.WarmEmissionAnalysisModule.(WarmEmissionAnalysisModule.java:171)
at org.matsim.contrib.emissions.WarmEmissionHandler.(WarmEmissionHandler.java:80)
at org.matsim.contrib.emissions.EmissionModule.createEmissionHandlers(EmissionModule.java:200)
at org.matsim.contrib.emissions.EmissionModule.(EmissionModule.java:74)
at org.matsim.contrib.emissions.EmissionModule$$FastClassByGuice$$3f5bb797.newInstance()
at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1050)
... 2 more

**Comment by neda-git** [comment]
Thanks @Nitnelav, I use hbefa 4.2 which doesn't contain some data such as the size class etc.. really it's not so easy.

**Comment by Nitnelav** [comment]
looking back at https://github.com/eqasim-org/ile-de-france/issues/159#issuecomment-1470178657
columns are good but you are using `,` as a decimal sign, try using `.` and see if it fixes your problem.
ie. replace `7,67883E-05` with `7.67883E-05`

**Comment by neda-git** [comment]
yeah, I already fixed this problem. If I use hbefa 3.3 instead of hbefa 4.2, in the TrafficScenario REF F HB42 will change to BAU F HB33, do you think it can happen the error?

**Comment by Nitnelav** [comment]
No I don't think so... in https://github.com/eqasim-org/ile-de-france/issues/159#issuecomment-1470178657 you show your cold detailed file, can you show the first line of your hot detailed one ?

**Comment by neda-git** [comment]
I used hbefa 3.3 to fill the size classe column, so it's my hot detailed:

Case;VehCat;Year;TrafficScenario;Component;RoadCat;TrafficSit;Gradient;IDSubsegment;Subsegment;Technology;SizeClasse;EmConcept;KM;%OfSubsegment;V;V_0%;V_100%;EFA;EFA_0%;EFA_100%;V_weighted_0%;V_weighted_100%;V_weighted_100%;EFA_weighted;EFA_weighted_0%;EFA_weighted_100%;AmbientCondPattern

2015_hot_detailed[3.3];pass. car;2010;;HC;;RUR/MW/80/Freeflow;0%;121220;PC diesel 1,4-<2L Euro-2;diesel;1,4-<2L;PC D Euro-2;50000;1;82.8059616088867;;;0.0275500006973743;;;;;;;;;ØFrance(Lille)

2015_hot_detailed[3.3];pass. car;2010;;HC;;RUR/MW/80/Freeflow;0%;121221;PC diesel 1,4-<2L Euro-2 (DPF);diesel;1,4-<2L;PC D Euro-2;50000;1;82.8059616088867;;;0.0275500006973743;;;;;;;;;ØFrance(Lille)

**Comment by Nitnelav** [comment]
I don't know for version 3.3. for version 4.2, are you using the same parameters as me here https://github.com/eqasim-org/ile-de-france/issues/159#issuecomment-1456470427 ? If not what are the differences ?

**Comment by neda-git** [comment]
my parameters:

![cold-av](https://user-images.githubusercontent.com/79261451/228570871-4a0990a1-b056-4903-be79-cfd65092ecbe.PNG)
![cold_de](https://user-images.githubusercontent.com/79261451/228571114-c984e6c8-2236-47d8-a9d1-f7715e2b409e.PNG)
![hot_av](https://user-images.githubusercontent.com/79261451/228571144-5b85dcff-bbda-4798-9fa9-4e9694670349.PNG)
![msg106526852-15244](https://user-images.githubusercontent.com/79261451/228571203-14518c20-6aaa-49e9-86eb-1f2e8d405ab3.jpg)

**Comment by Nitnelav** [comment]
ok well, try using only 2015 for all your exports and then try removing pollutants one b one to see if anything works, in the end if you mach my exports it should work..

**Comment by neda-git** [comment]
Thank you @Nitnelav for taking the time, I will do that, did you select all speed limit in individual TrafficSituations?

**Comment by Nitnelav** [comment]
I just checked I have all conditions selected,

**Comment by neda-git** [comment]
ok, Many thanks

**Comment by neda-git** [comment]
Hello @Nitnelav, I've successfully finished it. Now, I have the emissions events file. Many thanks for your support.

**Comment by Nitnelav** [comment]
Ah, I didn't see your edit...
the shpfile for --domain-shp-path should contain a single geometry (polygon) that represents the area you want to create the grid in.

**Comment by neda-git** [comment]
Thanks @Nitnelav
