### ISSUE TITLE
OutOfMemoryError when running the project

### ISSUE THREAD

**Issue by caizy1709** [eqasim-org/ile-de-france#206]
When I run the code, it prompts a memory error 'Exception in thread "main" java.lang.OutOfMemoryError: Java heap ', although I entered JAVA Memory: 8G in the config.yml file while the real memory is 12G.
The more detail is:
`Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
Traceback (most recent call last):
  File "/usr/local/envs/ile-de-france/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/envs/ile-de-france/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/envs/ile-de-france/lib/python3.10/site-packages/synpp/__main__.py", line 14, in <module>
    synpp.run_from_yaml(config_path)
  File "/usr/local/envs/ile-de-france/lib/python3.10/site-packages/synpp/pipeline.py", line 886, in run_from_yaml
    Synpp.build_from_yml(path).run_pipeline()
  File "/usr/local/envs/ile-de-france/lib/python3.10/site-packages/synpp/pipeline.py", line 910, in run_pipeline
    return run(definitions, self.config, self.working_directory, flowchart_path=flowchart_path,
  File "/usr/local/envs/ile-de-france/lib/python3.10/site-packages/synpp/pipeline.py", line 810, in run
    result = stage["wrapper"].execute(context)
  File "/usr/local/envs/ile-de-france/lib/python3.10/site-packages/synpp/pipeline.py", line 88, in execute
    return self.instance.execute(context)
  File "/content/drive/MyDrive/matsim/ile-de-france/matsim/scenario/supply/osm.py", line 57, in execute
    pt2matsim.run(context, "org.matsim.pt2matsim.run.Osm2MultimodalNetwork", 
  File "/content/drive/MyDrive/matsim/ile-de-france/matsim/runtime/pt2matsim.py", line 25, in run
    java.run(context, command, arguments, jar_path, vm_arguments)
  File "/content/drive/MyDrive/matsim/ile-de-france/matsim/runtime/java.py", line 52, in run
    return_code = sp.check_call(command_line, cwd = cwd)
  File "/usr/local/envs/ile-de-france/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/java', '-cp', '/usr/ile-de-france/cache/matsim.runtime.pt2matsim__f1350947cfdb4e14e8c57cf935423282.cache/pt2matsim/target/pt2matsim-22.3-shaded.jar', '-Xmx8G', '-Djava.io.tmpdir=/usr/ile-de-france/cache/matsim.scenario.supply.osm__f2b31f65d359ad58b12cbfe6f8987508.cache/__java_temp', '-Dmatsim.useLocalDtds=true', 'org.matsim.pt2matsim.run.Osm2MultimodalNetwork', 'config.xml']' returned non-zero exit status 1.`

**Comment by balacmi** [comment]
I guess 8G is not enough. Depending on the region you are trying to extract and the sample size you want to use, you would need a different amount of memory.
Try increasing it to 14G as default and see how it goes. If it fails, increasing it even more would eventually solve the problem.

**Comment by sebhoerl** [comment]
Please reopen if the problem has not been resolved.
